# Generated by Django 4.1.7 on 2023-10-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerRequest',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=40)),
                ('restaurantname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=70)),
                ('content', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
