# Generated by Django 4.1.7 on 2023-10-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyammaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllItems',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('itemname', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(default='upload-image', upload_to='lyammaApp/images')),
                ('explain', models.CharField(max_length=232)),
                ('slug', models.CharField(default='this-s', max_length=130)),
            ],
        ),
    ]
