# Generated by Django 4.1.7 on 2023-10-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyammaApp', '0002_allitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='launchPartner',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='upload-image', upload_to='lyammaApp/images')),
                ('fullname', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=30)),
                ('restaurantname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=70)),
                ('restauranttype', models.CharField(max_length=70)),
                ('slug', models.CharField(default='normal-slug', max_length=130)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
