# Generated by Django 4.1.7 on 2023-11-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyammaApp', '0003_launchpartner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=40)),
                ('cemail', models.CharField(max_length=100)),
                ('cphone', models.CharField(max_length=17)),
                ('content', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
